name: Pre Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Run Tests
        run: |
          yarn
          yarn test
        working-directory: ./tests

      - name: Run Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install Railway
        run: yarn global add @railway/cli

      - name: Deploy Email Workers
        run: |
          railway up -s "Growth App"
          railway up -s "Workers"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
